// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFacturacionSRI.Infrastructure.Data;

#nullable disable

namespace SistemaFacturacionSRI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Codigo");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "CAT-001",
                            Descripcion = "Categoría por defecto",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "General"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "CAT-002",
                            Descripcion = "Productos lácteos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lacteos"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "CAT-003",
                            Descripcion = "Carnes procesadas y embutidos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Embutidos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "CAT-004",
                            Descripcion = "Productos de cadena de frío",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Refrigerados"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "CAT-005",
                            Descripcion = "Conservas y alimentos enlatados",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Enlatados"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "CAT-006",
                            Descripcion = "Bebidas alcohólicas y no alcohólicas",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Codigo = "CAT-008",
                            Descripcion = "Productos de limpieza",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Codigo = "CAT-009",
                            Descripcion = "Cuidado personal e higiene",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Higiene"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Codigo = "CAT-010",
                            Descripcion = "Panes y repostería",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Panaderia"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Codigo = "CAT-011",
                            Descripcion = "Productos frescos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "FrutasVerduras"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Codigo = "CAT-012",
                            Descripcion = "Arroz, granos y legumbres secas",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Granos"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Codigo = "CAT-014",
                            Descripcion = "Galletas, confites y snacks empacados",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Snacks"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellidos = "Pérez",
                            Direccion = "Av. Amazonas 123, Quito",
                            Email = "juan.perez@example.com",
                            Identificacion = "0102030405",
                            Nombres = "Juan",
                            Telefono = "+593999999999",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellidos = "García",
                            Direccion = "Calle 10 de Agosto 456, Cuenca",
                            Email = "maria.garcia@example.com",
                            Identificacion = "0607080910",
                            Nombres = "María",
                            Telefono = "+593988888888",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellidos = "Lopez",
                            Direccion = "Av. 9 de Octubre 789, Guayaquil",
                            Email = "carlos.lopez@example.com",
                            Identificacion = "1718192021",
                            Nombres = "Carlos",
                            Telefono = "+593977777777",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 4,
                            Apellidos = "Salazar",
                            Direccion = "Av. de los Shyris 321, Quito",
                            Email = "andrea.salazar@example.com",
                            Identificacion = "2122232425",
                            Nombres = "Andrea",
                            Telefono = "+593966666666",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 5,
                            Apellidos = "Vera",
                            Direccion = "Km 6.5 Via Daule, Guayaquil",
                            Email = "miguel.vera@example.com",
                            Identificacion = "2627282930",
                            Nombres = "Miguel",
                            Telefono = "+593955555555",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 6,
                            Apellidos = "Ortiz",
                            Direccion = "Av. Loja 12-34, Loja",
                            Email = "fernanda.ortiz@example.com",
                            Identificacion = "3132333435",
                            Nombres = "Fernanda",
                            Telefono = "+593944444444",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 7,
                            Apellidos = "Cedeño",
                            Direccion = "Malecón 2000, Guayaquil",
                            Email = "jorge.cedeno@example.com",
                            Identificacion = "3637383940",
                            Nombres = "Jorge",
                            Telefono = "+593933333333",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 8,
                            Apellidos = "Morales",
                            Direccion = "Av. Pedro Vicente Maldonado 123, Latacunga",
                            Email = "lucia.morales@example.com",
                            Identificacion = "4142434445",
                            Nombres = "Lucía",
                            Telefono = "+593922222222",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 9,
                            Apellidos = "Suárez",
                            Direccion = "Av. Solano 987, Cuenca",
                            Email = "ricardo.suarez@example.com",
                            Identificacion = "4647484950",
                            Nombres = "Ricardo",
                            Telefono = "+593911111111",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 10,
                            Apellidos = "Martínez",
                            Direccion = "Av. Esmeraldas 456, Esmeraldas",
                            Email = "veronica.martinez@example.com",
                            Identificacion = "5152535455",
                            Nombres = "Verónica",
                            Telefono = "+593900000000",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 11,
                            Apellidos = "Aguirre",
                            Direccion = "Av. 6 de Diciembre 100, Quito",
                            Email = "patricio.aguirre@example.com",
                            Identificacion = "5657585960",
                            Nombres = "Patricio",
                            Telefono = "+593989898989",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 12,
                            Apellidos = "Reyes",
                            Direccion = "Ruta del Sol, Santa Elena",
                            Email = "gabriela.reyes@example.com",
                            Identificacion = "6162636465",
                            Nombres = "Gabriela",
                            Telefono = "+593979797979",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 13,
                            Apellidos = "Villalba",
                            Direccion = "Av. Universitaria 567, Ambato",
                            Email = "hector.villalba@example.com",
                            Identificacion = "6667686970",
                            Nombres = "Héctor",
                            Telefono = "+593969696969",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 14,
                            Apellidos = "Correa",
                            Direccion = "Av. González Suárez 135, Quito",
                            Email = "paola.correa@example.com",
                            Identificacion = "7172737475",
                            Nombres = "Paola",
                            Telefono = "+593959595959",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 15,
                            Apellidos = "Paredes",
                            Direccion = "Av. Amazonas y República, Quito",
                            Email = "diego.paredes@example.com",
                            Identificacion = "7677787980",
                            Nombres = "Diego",
                            Telefono = "+593949494949",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 16,
                            Apellidos = "Carrillo",
                            Direccion = "Av. Bolivariana 345, Riobamba",
                            Email = "natalia.carrillo@example.com",
                            Identificacion = "8182838485",
                            Nombres = "Natalia",
                            Telefono = "+593939393939",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 17,
                            Apellidos = "Yánez",
                            Direccion = "Av. Manabí 456, Portoviejo",
                            Email = "sebastian.yanez@example.com",
                            Identificacion = "8687888990",
                            Nombres = "Sebastián",
                            Telefono = "+593929292929",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 18,
                            Apellidos = "Pico",
                            Direccion = "Av. 24 de Mayo 678, Ibarra",
                            Email = "daniela.pico@example.com",
                            Identificacion = "9192939495",
                            Nombres = "Daniela",
                            Telefono = "+593919191919",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 19,
                            Apellidos = "Montero",
                            Direccion = "Av. Quito 123, Santo Domingo",
                            Email = "gustavo.montero@example.com",
                            Identificacion = "9697989991",
                            Nombres = "Gustavo",
                            Telefono = "+593909090909",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 20,
                            Apellidos = "Peñafiel",
                            Direccion = "Av. Olmedo 345, Machala",
                            Email = "silvia.penafiel@example.com",
                            Identificacion = "0192837465",
                            Nombres = "Silvia",
                            Telefono = "+593998877665",
                            TipoIdentificacionId = 2
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<string>("ClaveAccesoSRI")
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Emitida");

                    b.Property<string>("EstadoSRI")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("ClaveAccesoSRI")
                        .IsUnique()
                        .HasFilter("[ClaveAccesoSRI] IS NOT NULL");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Property<int>("FacturaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaLinea")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturaDetalles", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PVP")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("TipoIVAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Productos_Codigo");

                    b.HasIndex("TipoIVAId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIVACatalogo", b =>
                {
                    b.Property<int>("TipoIVAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIVAId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("TipoIVAId");

                    b.ToTable("TiposIVA", (string)null);

                    b.HasData(
                        new
                        {
                            TipoIVAId = 1,
                            Descripcion = "IVA 0%",
                            Porcentaje = 0m
                        },
                        new
                        {
                            TipoIVAId = 2,
                            Descripcion = "IVA 5%",
                            Porcentaje = 5m
                        },
                        new
                        {
                            TipoIVAId = 3,
                            Descripcion = "IVA 8%",
                            Porcentaje = 8m
                        },
                        new
                        {
                            TipoIVAId = 6,
                            Descripcion = "IVA 15%",
                            Porcentaje = 15m
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Property<int>("TipoIdentificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIdentificacionId"));

                    b.Property<string>("CodigoSRI")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoIdentificacionId");

                    b.ToTable("TiposIdentificacion", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_TipoIdentificacion");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Cliente");

                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Factura");

                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Producto");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Lote", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lote_Producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.TipoIVACatalogo", "TipoIVACatalogo")
                        .WithMany("Productos")
                        .HasForeignKey("TipoIVAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Productos_TiposIVA");

                    b.Navigation("Categoria");

                    b.Navigation("TipoIVACatalogo");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIVACatalogo", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
