// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFacturacionSRI.Infrastructure.Data;

#nullable disable

namespace SistemaFacturacionSRI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Codigo");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "CAT-001",
                            Descripcion = "Categoría por defecto",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "General"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "CAT-002",
                            Descripcion = "Productos lácteos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lacteos"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "CAT-003",
                            Descripcion = "Carnes procesadas y embutidos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Embutidos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "CAT-004",
                            Descripcion = "Productos de cadena de frío",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Refrigerados"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "CAT-005",
                            Descripcion = "Conservas y alimentos enlatados",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Enlatados"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "CAT-006",
                            Descripcion = "Bebidas alcohólicas y no alcohólicas",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Codigo = "CAT-008",
                            Descripcion = "Productos de limpieza",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Codigo = "CAT-009",
                            Descripcion = "Cuidado personal e higiene",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Higiene"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Codigo = "CAT-010",
                            Descripcion = "Panes y repostería",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Panaderia"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Codigo = "CAT-011",
                            Descripcion = "Productos frescos",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "FrutasVerduras"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Codigo = "CAT-012",
                            Descripcion = "Arroz, granos y legumbres secas",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Granos"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Codigo = "CAT-014",
                            Descripcion = "Galletas, confites y snacks empacados",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Snacks"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.CertificadoDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("ArchivoEncriptado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ClaveEncriptada")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PRUEBAS");

                    b.HasKey("Id");

                    b.HasIndex("EsActivo", "Tipo")
                        .HasDatabaseName("IX_CertificadosDigitales_ActivosPorTipo");

                    b.ToTable("CertificadosDigitales", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido1 = "Perez",
                            Direccion = "Av. Amazonas 123, Quito",
                            Email = "juan.perez@example.com",
                            Estado = true,
                            Identificacion = "0102030405",
                            Nombre1 = "Juan",
                            Telefono = "0991110001",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellido1 = "Garcia",
                            Direccion = "Calle 10 de Agosto 456, Cuenca",
                            Email = "maria.garcia@example.com",
                            Estado = true,
                            Identificacion = "0607080910",
                            Nombre1 = "Maria",
                            Telefono = "0991110002",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellido1 = "Lopez",
                            Direccion = "Av. 9 de Octubre 789, Guayaquil",
                            Email = "carlos.lopez@example.com",
                            Estado = true,
                            Identificacion = "1718192021",
                            Nombre1 = "Carlos",
                            Telefono = "0991110003",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 4,
                            Apellido1 = "Salazar",
                            Direccion = "Av. de los Shyris 321, Quito",
                            Email = "andrea.salazar@example.com",
                            Estado = true,
                            Identificacion = "2122232425",
                            Nombre1 = "Andrea",
                            Telefono = "0991110004",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 5,
                            Apellido1 = "Vera",
                            Direccion = "Km 6.5 Via Daule, Guayaquil",
                            Email = "miguel.vera@example.com",
                            Estado = true,
                            Identificacion = "2627282930",
                            Nombre1 = "Miguel",
                            Telefono = "0991110005",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 6,
                            Apellido1 = "Ortiz",
                            Direccion = "Av. Loja 12-34, Loja",
                            Email = "fernanda.ortiz@example.com",
                            Estado = true,
                            Identificacion = "3132333435",
                            Nombre1 = "Fernanda",
                            Telefono = "0991110006",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 7,
                            Apellido1 = "Cedeno",
                            Direccion = "Malecon 2000, Guayaquil",
                            Email = "jorge.cedeno@example.com",
                            Estado = true,
                            Identificacion = "3637383940",
                            Nombre1 = "Jorge",
                            Telefono = "0991110007",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 8,
                            Apellido1 = "Morales",
                            Direccion = "Av. Pedro Vicente Maldonado 123, Latacunga",
                            Email = "lucia.morales@example.com",
                            Estado = true,
                            Identificacion = "4142434445",
                            Nombre1 = "Lucia",
                            Telefono = "0991110008",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 9,
                            Apellido1 = "Suarez",
                            Direccion = "Av. Solano 987, Cuenca",
                            Email = "ricardo.suarez@example.com",
                            Estado = true,
                            Identificacion = "4647484950",
                            Nombre1 = "Ricardo",
                            Telefono = "0991110009",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 10,
                            Apellido1 = "Martinez",
                            Direccion = "Av. Esmeraldas 456, Esmeraldas",
                            Email = "veronica.martinez@example.com",
                            Estado = true,
                            Identificacion = "5152535455",
                            Nombre1 = "Veronica",
                            Telefono = "0991110010",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 11,
                            Apellido1 = "Aguirre",
                            Direccion = "Av. 6 de Diciembre 100, Quito",
                            Email = "patricio.aguirre@example.com",
                            Estado = true,
                            Identificacion = "5657585960",
                            Nombre1 = "Patricio",
                            Telefono = "0991110011",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 12,
                            Apellido1 = "Reyes",
                            Direccion = "Ruta del Sol, Santa Elena",
                            Email = "gabriela.reyes@example.com",
                            Estado = true,
                            Identificacion = "6162636465",
                            Nombre1 = "Gabriela",
                            Telefono = "0991110012",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 13,
                            Apellido1 = "Villalba",
                            Direccion = "Av. Universitaria 567, Ambato",
                            Email = "hector.villalba@example.com",
                            Estado = true,
                            Identificacion = "6667686970",
                            Nombre1 = "Hector",
                            Telefono = "0991110013",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 14,
                            Apellido1 = "Correa",
                            Direccion = "Av. Gonzalez Suarez 135, Quito",
                            Email = "paola.correa@example.com",
                            Estado = true,
                            Identificacion = "7172737475",
                            Nombre1 = "Paola",
                            Telefono = "0991110014",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 15,
                            Apellido1 = "Paredes",
                            Direccion = "Av. Amazonas y Republica, Quito",
                            Email = "diego.paredes@example.com",
                            Estado = true,
                            Identificacion = "7677787980",
                            Nombre1 = "Diego",
                            Telefono = "0991110015",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 16,
                            Apellido1 = "Carrillo",
                            Direccion = "Av. Bolivariana 345, Riobamba",
                            Email = "natalia.carrillo@example.com",
                            Estado = true,
                            Identificacion = "8182838485",
                            Nombre1 = "Natalia",
                            Telefono = "0991110016",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 17,
                            Apellido1 = "Yanez",
                            Direccion = "Av. Manabi 456, Portoviejo",
                            Email = "sebastian.yanez@example.com",
                            Estado = true,
                            Identificacion = "8687888990",
                            Nombre1 = "Sebastian",
                            Telefono = "0991110017",
                            TipoIdentificacionId = 2
                        },
                        new
                        {
                            ClienteId = 18,
                            Apellido1 = "Pico",
                            Direccion = "Av. 24 de Mayo 678, Ibarra",
                            Email = "daniela.pico@example.com",
                            Estado = true,
                            Identificacion = "9192939495",
                            Nombre1 = "Daniela",
                            Telefono = "0991110018",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 19,
                            Apellido1 = "Montero",
                            Direccion = "Av. Quito 123, Santo Domingo",
                            Email = "gustavo.montero@example.com",
                            Estado = true,
                            Identificacion = "9697989991",
                            Nombre1 = "Gustavo",
                            Telefono = "0991110019",
                            TipoIdentificacionId = 1
                        },
                        new
                        {
                            ClienteId = 20,
                            Apellido1 = "Penafiel",
                            Direccion = "Av. Olmedo 345, Machala",
                            Email = "silvia.penafiel@example.com",
                            Estado = true,
                            Identificacion = "0192837465",
                            Nombre1 = "Silvia",
                            Telefono = "0991110020",
                            TipoIdentificacionId = 2
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica si el registro está activo");

                    b.Property<string>("AgenteRetencion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Resolución de agente de retención");

                    b.Property<string>("AmbienteSRI")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("1")
                        .HasComment("1=Pruebas, 2=Producción");

                    b.Property<string>("ClaveCertificadoDigital")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Contraseña del certificado (encriptada)");

                    b.Property<string>("CodigoEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength()
                        .HasComment("Código del establecimiento (ej: 001)");

                    b.Property<string>("ContribuyenteEspecial")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número de resolución de Contribuyente Especial");

                    b.Property<string>("DirEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Dirección del establecimiento");

                    b.Property<string>("DirMatriz")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Dirección de la matriz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Email de contacto");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha de creación del registro");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de última modificación");

                    b.Property<string>("InfoAdicionalDefecto")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Información adicional por defecto");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Ruta del logo para RIDE");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Nombre comercial de la empresa");

                    b.Property<bool>("ObligadoContabilidad")
                        .HasColumnType("bit")
                        .HasComment("Indica si está obligado a llevar contabilidad");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength()
                        .HasComment("Punto de emisión (ej: 001)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasComment("RUC de la empresa emisora (13 dígitos)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Razón social de la empresa");

                    b.Property<string>("RegimenRimpe")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Régimen RIMPE del contribuyente");

                    b.Property<string>("RutaCertificadoDigital")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Ruta del archivo del certificado digital (.p12)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Teléfono de contacto");

                    b.Property<string>("TipoEmision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("1")
                        .HasComment("1=Normal, 2=Indisponibilidad");

                    b.Property<string>("UrlAutorizacionComprobantes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("URL WebService Autorización SRI");

                    b.Property<string>("UrlRecepcionComprobantes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("URL WebService Recepción SRI");

                    b.HasKey("Id");

                    b.HasIndex("RUC")
                        .IsUnique()
                        .HasDatabaseName("IX_ConfiguracionEmpresa_RUC");

                    b.ToTable("ConfiguracionEmpresa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AgenteRetencion = "1",
                            AmbienteSRI = "1",
                            CodigoEstablecimiento = "001",
                            DirEstablecimiento = "Av. Principal 123 y Secundaria, Local 001",
                            DirMatriz = "Av. Principal 123 y Secundaria, Edificio Central",
                            Email = "facturacion@empresademo.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaModificacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InfoAdicionalDefecto = "Gracias por su compra|Términos y condiciones: www.empresademo.com/terminos",
                            NombreComercial = "DEMO FACTURACIÓN",
                            ObligadoContabilidad = true,
                            PuntoEmision = "001",
                            RUC = "1804183794001",
                            RazonSocial = "EMPRESA DEMO FACTURACIÓN ELECTRÓNICA S.A.",
                            Telefono = "03-2345678",
                            TipoEmision = "1",
                            UrlAutorizacionComprobantes = "https://celportal.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl",
                            UrlRecepcionComprobantes = "https://celportal.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,4)");

                    b.Property<string>("CodigoAuxiliar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodigoPorcentajeIVA")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("CodigoPrincipal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioTotalSinImpuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarifa")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("FacturaId", "ProductoId")
                        .HasDatabaseName("IX_FacturaDetalles_FacturaId_ProductoId");

                    b.ToTable("FacturaDetalles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            BaseImponible = 100m,
                            Cantidad = 2m,
                            CodigoAuxiliar = "SKU-001",
                            CodigoPorcentajeIVA = 15,
                            CodigoPrincipal = "PRD-001",
                            Descripcion = "Producto demo rechazado",
                            Descuento = 0m,
                            FacturaId = 1001,
                            FechaCreacion = new DateTime(2024, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            PrecioTotalSinImpuesto = 100m,
                            PrecioUnitario = 50m,
                            Tarifa = 15m,
                            Valor = 15m,
                            ValorTotal = 115m
                        },
                        new
                        {
                            Id = 2002,
                            BaseImponible = 85m,
                            Cantidad = 3m,
                            CodigoAuxiliar = "SKU-002",
                            CodigoPorcentajeIVA = 15,
                            CodigoPrincipal = "PRD-002",
                            Descripcion = "Producto demo devuelto",
                            Descuento = 5m,
                            FacturaId = 1002,
                            FechaCreacion = new DateTime(2024, 11, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            PrecioTotalSinImpuesto = 90m,
                            PrecioUnitario = 30m,
                            Tarifa = 15m,
                            Valor = 12.75m,
                            ValorTotal = 97.75m
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaveAcceso")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("nvarchar(49)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BORRADOR");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuiaRemision")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)")
                        .HasComment("Número de Guía de Remisión asociada");

                    b.Property<decimal>("IVA15")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("MensajesSRI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Propina")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Subtotal0")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Subtotal15")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("SubtotalConDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("SubtotalExentoIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("SubtotalNoObjetoIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("TipoEmision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("XmlFirmadoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("XmlPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClaveAcceso")
                        .IsUnique()
                        .HasDatabaseName("IX_Facturas_ClaveAcceso");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Facturas_Estado");

                    b.HasIndex("FechaEmision")
                        .HasDatabaseName("IX_Facturas_FechaEmision");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("IX_Facturas_NumeroFactura");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Ambiente = "PRUEBAS",
                            ClaveAcceso = "1234567890123456789012345678901234567890123456789",
                            ClienteId = 1,
                            Descuento = 0m,
                            Estado = "NO_AUTORIZADA",
                            FechaCreacion = new DateTime(2024, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            FechaEmision = new DateTime(2024, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            FechaModificacion = new DateTime(2024, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IVA15 = 15m,
                            ImporteTotal = 115m,
                            MensajesSRI = "ERROR 70: Clave de acceso inválida",
                            NumeroFactura = "001-001-000000101",
                            Observaciones = "Factura de prueba rechazada por el SRI",
                            PdfPath = "comprobantes/pdf/RIDE_1234567890123456789012345678901234567890123456789.pdf",
                            Propina = 0m,
                            Subtotal0 = 0m,
                            Subtotal15 = 100m,
                            SubtotalConDescuento = 100m,
                            SubtotalExentoIVA = 0m,
                            SubtotalNoObjetoIVA = 0m,
                            TipoEmision = "NORMAL",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 1002,
                            Ambiente = "PRUEBAS",
                            ClaveAcceso = "9876543210987654321098765432109876543210987654321",
                            ClienteId = 2,
                            Descuento = 5m,
                            Estado = "DEVUELTA",
                            FechaCreacion = new DateTime(2024, 11, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            FechaEmision = new DateTime(2024, 11, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            FechaModificacion = new DateTime(2024, 11, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            IVA15 = 12.75m,
                            ImporteTotal = 97.75m,
                            MensajesSRI = "DEVUELTA: Falta detalle de impuestos",
                            NumeroFactura = "001-001-000000102",
                            Observaciones = "Factura de prueba devuelta para corrección",
                            Propina = 0m,
                            Subtotal0 = 0m,
                            Subtotal15 = 90m,
                            SubtotalConDescuento = 85m,
                            SubtotalExentoIVA = 0m,
                            SubtotalNoObjetoIVA = 0m,
                            TipoEmision = "NORMAL",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.InfoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId", "Nombre")
                        .HasDatabaseName("IX_InfoAdicional_FacturaId_Nombre");

                    b.ToTable("InfoAdicional", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3001,
                            FacturaId = 1001,
                            Nombre = "motivo",
                            Valor = "Clave de acceso observada"
                        },
                        new
                        {
                            Id = 3002,
                            FacturaId = 1002,
                            Nombre = "motivo",
                            Valor = "Documento devuelto para corrección"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PVP")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Productos_Codigo");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            NombreRol = "Vendedor"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.SecuenciaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("FechaUltimaEmision")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("SecuenciaActual")
                        .HasColumnType("BIGINT");

                    b.HasKey("Id");

                    b.HasIndex("Establecimiento", "PuntoEmision")
                        .IsUnique();

                    b.ToTable("SecuenciasFactura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Establecimiento = "001",
                            PuntoEmision = "001",
                            SecuenciaActual = 0L
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIVACatalogo", b =>
                {
                    b.Property<int>("TipoIVAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIVAId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("TipoIVAId");

                    b.ToTable("TiposIVA", (string)null);

                    b.HasData(
                        new
                        {
                            TipoIVAId = 1,
                            Descripcion = "IVA 0%",
                            Porcentaje = 0m
                        },
                        new
                        {
                            TipoIVAId = 2,
                            Descripcion = "IVA 5%",
                            Porcentaje = 5m
                        },
                        new
                        {
                            TipoIVAId = 3,
                            Descripcion = "IVA 8%",
                            Porcentaje = 8m
                        },
                        new
                        {
                            TipoIVAId = 6,
                            Descripcion = "IVA 15%",
                            Porcentaje = 15m
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Property<int>("TipoIdentificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIdentificacionId"));

                    b.Property<string>("CodigoSRI")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoIdentificacionId");

                    b.ToTable("TiposIdentificacion", (string)null);

                    b.HasData(
                        new
                        {
                            TipoIdentificacionId = 1,
                            CodigoSRI = "05",
                            Nombre = "Cedula"
                        },
                        new
                        {
                            TipoIdentificacionId = 2,
                            CodigoSRI = "04",
                            Nombre = "RUC"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido1 = "Principal",
                            Cedula = "0102030405",
                            Direccion = "Oficina Matriz",
                            Email = "admin@sistemafacturacion.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosLogin = 0,
                            Nombre1 = "Admin",
                            Nombre2 = "Sistema",
                            PasswordHash = "ClvD40JDLxutkv/VG3hTQ+xykGzbpqJhMQYLAI54ZlY=",
                            RolId = 1,
                            Telefono = "0991234567",
                            Username = "admin"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellido1 = "Principal",
                            Cedula = "0607080910",
                            Direccion = "Sucursal Centro",
                            Email = "vendedor@sistemafacturacion.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosLogin = 0,
                            Nombre1 = "Vendedor",
                            Nombre2 = "Demo",
                            PasswordHash = "K6FhJ3pkkLQo6VCZ1hH4zmlxqxgAYleOSmCmjrxdWa8=",
                            RolId = 2,
                            Telefono = "0987654321",
                            Username = "vendedor1"
                        });
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_TipoIdentificacion");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFactura_Factura");

                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DetalleFactura_Producto");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.InfoAdicional", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Factura", "Factura")
                        .WithMany("InfoAdicional")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Lote", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lote_Producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaFacturacionSRI.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("InfoAdicional");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaFacturacionSRI.Domain.Entities.TipoIdentificacion", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
